name: build-deploy-gh-pages

on:
  push:
    branches:
      - main

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: run deploy.sh
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: ./deploy.sh

