name: build-deploy-gh-pages

on:
  push:
    branches:
      - main

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: build
        run: yarn && yarn build
      - name: git
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          cd dist
          git config --global user.email "{{ github.actor }}@users.noreply.github.com"
          git config --global user.name "{{ github.actor }}"
          git add -A
          git commit -m "Deploy to GitHub Pages"
          git push -f git@github.com:zlx01/qingtian.git main:gh-pages
